name: Build and Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore: 
      - .github/workflows/*
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - .github/workflows/*
  release:
    types: [created]
  

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore Flow.Launcher.Plugin.OpenWindowSearch.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore Flow.Launcher.Plugin.OpenWindowSearch.csproj

    - name: Test
      run: dotnet test --no-restore --verbosity normal Flow.Launcher.Plugin.OpenWindowSearch.csproj

    - name: Publish
      if: github.event_name == 'release'
      run: dotnet publish --configuration Release --output ./publish Flow.Launcher.Plugin.OpenWindowSearch.csproj

    - name: Zip Release
      if: github.event_name == 'release'
      run: Compress-Archive -Path ./publish/* -DestinationPath ./Flow.Launcher.Plugin.OpenWindowSearch.zip
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'plugin.json'
        prop_path: 'Version'
    - name: Publish
      if: github.event_name == 'release' && success()
      uses: softprops/action-gh-release@v1
      with:
        files: 'Flow.Launcher.Plugin.OpenWindowSearch.zip'
        tag_name: "v${{steps.version.outputs.prop}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}