name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      if: github.event_name == 'release'
      run: dotnet publish --configuration Release --output ./publish

    - name: Zip Release
      if: github.event_name == 'release'
      run: Compress-Archive -Path ./publish/* -DestinationPath ./Flow.Launcher.Plugin.OpenWindowSearch.zip

    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Flow.Launcher.Plugin.OpenWindowSearch.zip
        asset_name: Flow.Launcher.Plugin.OpenWindowSearch.zip
        asset_content_type: application/zip